// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace KoduAnalytics.ProgramAnalytics
{
    public static class Utils
    {


        public static Tile[] upidDeprecated = {
                                                   new Tile( "filter.nothing", TileData.filter, -1),
                                                    new Tile("filter.boku", TileData.filter, -1),
                                                    new Tile("filter.countnone", TileData.filter, -1),
                                                    new Tile("filter.stick",  TileData.filter, -1),
                                                    new Tile("filter.flower", TileData.filter, -1),
                                                    new Tile("filter.gate", TileData.filter, -1),
                                                    new Tile("filter.pathplain", TileData.filter, -1),
                                                    new Tile("filter.pathroad", TileData.filter, -1),
                                                    new Tile("filter.pathwall", TileData.filter, -1),
                                                    new Tile("filter.pathflora", TileData.filter, -1),
                                                    new Tile("filter.yucca1", TileData.filter, -1),
                                                    new Tile("filter.yucca2", TileData.filter, -1),
                                                    new Tile("filter.yucca3", TileData.filter, -1),
                                                    new Tile("filter.bigyucca1", TileData.filter, -1),
                                                    new Tile("filter.expressnormal", TileData.filter, -1),
                                                    new Tile("filter.lefttrigger", TileData.filter, -1),
                                                    new Tile("filter.righttrigger", TileData.filter, -1),
                                                    new Tile("filter.scoretrigger", TileData.filter, -1),
                                                    new Tile("selector.cruise", TileData.selector, -1),
                                                    new Tile("selector.spin",TileData.selector, -1),
                                                    new Tile("selector.escape",TileData.selector, -1),
                                                    new Tile("selector.moveleftright",TileData.selector, -1),
                                                    new Tile("modifier.speednormally", TileData.modifer, -1),
                                                    new Tile("modifier.strengthnormally", TileData.modifer, -1),
                                                    new Tile("modifier.pitchup", TileData.modifer, -1),
                                                    new Tile("modifier.pitchdown", TileData.modifer, -1),
                                                    new Tile("modifier.teama", TileData.modifer, -1),
                                                    new Tile("modifier.teamb", TileData.modifer, -1),
                                                    new Tile("modifier.constraint.leftright", TileData.modifer, -1),
                                                    new Tile("modifier.constraint.fwdback", TileData.modifer, -1),
                                                    new Tile("modifier.constraint.updown", TileData.modifer, -1),
                                                    new Tile("actuator.nothing", TileData.actuator, -1),
                                                    new Tile("actuator.kick", TileData.actuator, -1),
                                                    new Tile("actuator.watersurface", TileData.actuator, -1),
                                                    new Tile("actuator.waterdive", TileData.actuator, -1),
                                                    new Tile("actuator.airrise", TileData.actuator, -1),
                                                    new Tile("actuator.airdrop", TileData.actuator, -1),
                                                    new Tile("actuator.shoot", TileData.actuator, -1),
                                                    new Tile("actuator.restart", TileData.actuator, -1),
                                                };

        public static Tile[] upidActuators = {
                                                   new Tile("actuator.camera.firstperson", TileData.actuator, 2),
                                                   new Tile("actuator.camera.ignoreme", TileData.actuator, 2),
                                                   new Tile("actuator.camera.followme", TileData.actuator, 2),
                                                   new Tile("actuator.unscore", TileData.actuator, 2),
                                                   new Tile("actuator.score", TileData.actuator, 2),
                                                   new Tile("actuator.victory", TileData.actuator, 2),
                                                   new Tile("actuator.gameover", TileData.actuator, 2),
                                                   new Tile("actuator.restart", TileData.actuator, -1),
                                                   new Tile("actuator.reset", TileData.actuator, 2), //this is current
                                                   new Tile("actuator.give", TileData.actuator, 2),
                                                   new Tile("actuator.drop", TileData.actuator, 2),
                                                   new Tile("actuator.grab", TileData.actuator, 2),
                                                   new Tile("actuator.vanish", TileData.actuator, 2),
                                                   new Tile("actuator.boom", TileData.actuator, 2),
                                                   new Tile("actuator.pop", TileData.actuator, 2),
                                                   new Tile("actuator.zap", TileData.actuator, 2),
                                                   new Tile("actuator.heal", TileData.actuator, 2),
                                                   new Tile("actuator.damage", TileData.actuator, 2),
                                                   new Tile("actuator.shoot2", TileData.actuator, 1), //this is the current shoot
                                                   new Tile("actuator.shoot", TileData.actuator, -1),
                                                   new Tile("actuator.switchtask", TileData.actuator, 1),
                                                   new Tile("actuator.airdrop", TileData.actuator, -1),
                                                   new Tile("actuator.airrise", TileData.actuator, -1),
                                                   new Tile("actuator.waterdive", TileData.actuator, -1),
                                                   new Tile("actuator.watersurface", TileData.actuator, -1),
                                                   new Tile("actuator.jump", TileData.actuator, -1),
                                                   new Tile("actuator.stopsound", TileData.actuator, 2),
                                                   new Tile("actuator.sound", TileData.actuator, 2),
                                                   new Tile("actuator.glow", TileData.actuator, 2),
                                                   new Tile("actuator.color", TileData.actuator, 2),
                                                   new Tile("actuator.express", TileData.actuator, 2),
                                                   new Tile("actuator.launch", TileData.actuator, 2),
                                                   new Tile("actuator.make", TileData.actuator, 2),
                                                   new Tile("actuator.kick", TileData.actuator, -1),
                                                   new Tile("actuator.close", TileData.actuator, 2),
                                                   new Tile("actuator.open", TileData.actuator, 2),
                                                   new Tile("actuator.say", TileData.actuator, 2),
                                                   new Tile("actuator.eat", TileData.actuator, 1),
                                                   new Tile("actuator.turn", TileData.actuator, 1),
                                                   new Tile("actuator.movement", TileData.actuator, 1),
                                                   new Tile("actuator.nothing", TileData.actuator, -1),
                                               };
        /*
         * -1: deprecated
         * 0: hidden default
         * 1: first pie
         * 2: second pie
         */
        public static Tile[] upidSelectors = {
                                                   new Tile("selector.closest",  TileData.selector, 0),
                                                   new Tile("selector.objectrelative", TileData.selector, 0),
                                                   new Tile("selector.towardclosest", TileData.selector, 1),
                                                   new Tile("selector.awayfromall", TileData.selector, 1),
                                                   new Tile("selector.avoidall", TileData.selector, 1),
                                                   new Tile("selector.wander", TileData.selector, 1),
                                                   new Tile("selector.cruise", TileData.selector, -1), //
                                                   new Tile("selector.circle", TileData.selector, 1),
                                                   new Tile("selector.spin", TileData.selector, 1), //
                                                   new Tile("selector.forward", TileData.selector, 1),
                                                   new Tile("selector.hiddenturn", TileData.selector, 0),
                                                   new Tile("selector.escape", TileData.selector, -1), //
                                                   new Tile("selector.followwaypoints", TileData.selector, 1),
                                                   new Tile("selector.moveupdown", TileData.selector, 1), //jet, on gamepad
                                                   new Tile("selector.moveup", TileData.selector, 1), // wisp
                                                   new Tile("selector.movedown", TileData.selector, 1), // wisp
                                                   new Tile("selector.moveleftright", TileData.selector, -1), //

                                               };

        public static String[] upidSensors = {
                                                 "sensor.gamepad",
                                                 "sensor.keyboard",
                                                 "sensor.mouse",
                                                 "sensor.eyes",
                                                 "sensor.ears",
                                                 "sensor.bumpers",
                                                 "sensor.timer",
                                                 "sensor.got",
                                                 "sensor.scored",
                                                 "sensor.health",
                                                 "sensor.missilehit",
                                                 "sensor.held",
                                                 "sensor.terrain",
                                                 "sensor.water",
                                                 "sensor.always",
                                             };
        public static String[] upidFilters = {
                                                 "filter.nothing",
                                                 "filter.boku",
                                                 "filter.bokubot",
                                                 "filter.anything",
                                                 "filter.me",
                                                 "filter.countnone",
                                                 "filter.flyfish",
                                                 "filter.jet",
                                                 "filter.light",
                                                 "filter.fastbot",
                                                 "filter.saucer",
                                                 "filter.windblimp",
                                                 "filter.balloonbot",
                                                 "filter.subbot",
                                                 "filter.terracannon",
                                                 "filter.puck",
                                                 "filter.wisp",
                                                 "filter.anybot",
                                                 "filter.turtle",
                                                 "filter.pushpad",
                                                 "filter.sputnik",
                                                 "filter.stick",
                                                 "filter.stickboy",
                                                 "filter.drum",
                                                 "filter.mine",
                                                 "filter.cloud",
                                                 "filter.swimfish",
                                                 "filter.floatbot",
                                                 "filter.factory",
                                                 "filter.hut",
                                                 "filter.castle",
                                                 "filter.fruit",
                                                 "filter.pipe",
                                                 "filter.pipeStraight",
                                                 "filter.pipeCross",
                                                 "filter.pipeCorner",
                                                 "filter.rock",
                                                 "filter.rockLowValue",
                                                 "filter.rockHighValue",
                                                 "filter.rockLowValueUnknown",
                                                 "filter.rockHighValueUnknown",
                                                 "filter.rockUnknown",
                                                 "filter.tree",
                                                 "filter.building",
                                                 "filter.flower",
                                                 "filter.gate",
                                                 "filter.cursor",
                                                 "filter.star",
                                                 "filter.coin",
                                                 "filter.soccerball",
                                                 "filter.heart",
                                                 "filter.bullet",
                                                 "filter.Black",
                                                 "filter.Grey",
                                                 "filter.white",
                                                 "filter.red",
                                                 "filter.orange",
                                                 "filter.yellow",
                                                 "filter.green",
                                                 "filter.blue",
                                                 "filter.purple",
                                                 "filter.pink",
                                                 "filter.brown",
                                                 "filter.pathplain",
                                                 "filter.pathroad",
                                                 "filter.pathwall",
                                                 "filter.pathflora",
                                                 "filter.yucca1",
                                                 "filter.yucca2",
                                                 "filter.yucca3",
                                                 "filter.bigyucca1",
                                                 "filter.expresshappy",
                                                 "filter.expresssad",
                                                 "filter.expressangry",
                                                 "filter.expresscrazy",
                                                 "filter.expresshearts",
                                                 "filter.expressflowers",
                                                 "filter.expressstars",
                                                 "filter.expressswear",
                                                 "filter.expressnormal",
                                                 "filter.expressnone",
                                                 "filter.closeby",
                                                 "filter.faraway",
                                                 "filter.countfew",
                                                 "filter.countmany",
                                                 "filter.countany",
                                                 "filter.leftstick",
                                                 "filter.rightstick",
                                                 "filter.abutton",
                                                 "filter.bbutton",
                                                 "filter.xbutton",
                                                 "filter.ybutton",
                                                 "filter.lefttrigger",
                                                 "filter.righttrigger",
                                                 "filter.lefttrigger_analog",
                                                 "filter.righttrigger_analog",
                                                 "filter.mouse.button.left",
                                                 "filter.mouse.button.right",
                                                 "filter.mouse.hover",
                                                 "filter.mouse.move",
                                                 "filter.Akey",
                                                 "filter.Bkey",
                                                 "filter.Ckey",
                                                 "filter.Dkey",
                                                 "filter.Ekey",
                                                 "filter.Fkey",
                                                 "filter.Gkey",
                                                 "filter.Hkey",
                                                 "filter.Ikey",
                                                 "filter.Jkey",
                                                 "filter.Kkey",
                                                 "filter.Lkey",
                                                 "filter.Mkey",
                                                 "filter.Nkey",
                                                 "filter.Okey",
                                                 "filter.Pkey",
                                                 "filter.Qkey",
                                                 "filter.Rkey",
                                                 "filter.Skey",
                                                 "filter.Tkey",
                                                 "filter.Ukey",
                                                 "filter.Vkey",
                                                 "filter.Wkey",
                                                 "filter.Xkey",
                                                 "filter.Ykey",
                                                 "filter.Zkey",
                                                 "filter.D0key",
                                                 "filter.D1key",
                                                 "filter.D2key",
                                                 "filter.D3key",
                                                 "filter.D4key",
                                                 "filter.D5key",
                                                 "filter.D6key",
                                                 "filter.D7key",
                                                 "filter.D8key",
                                                 "filter.D9key",
                                                 "filter.Spacekey",
                                                 "filter.PageUpkey",
                                                 "filter.PageDownkey",
                                                 "filter.Endkey",
                                                 "filter.Leftkey",
                                                 "filter.Upkey",
                                                 "filter.Rightkey",
                                                 "filter.Downkey",
                                                 "filter.Insertkey",
                                                 "filter.Deletekey",
                                                 "filter.LeftWindowskey",
                                                 "filter.RightWindowskey",
                                                 "filter.Multiplykey",
                                                 "filter.Addkey",
                                                 "filter.Subtractkey",
                                                "filter.Decimalkey",
                                                "filter.Dividekey",
                                                "filter.LeftShiftkey",
                                                "filter.RightShiftkey",
                                                "filter.LeftControlkey",
                                                "filter.RightControlkey",
                                                "filter.LeftAltkey",
                                                "filter.RightAltkey",
                                                "filter.OemSemicolonkey",
                                                "filter.OemPluskey",
                                                "filter.OemCommakey",
                                                "filter.OemMinuskey",
                                                "filter.OemPeriodkey",
                                                "filter.OemQuestionkey",
                                                "filter.OemTildekey",
                                                "filter.OemOpenBracketskey",
                                                "filter.OemPipekey",
                                                "filter.OemCloseBracketskey",
                                                "filter.OemQuoteskey",
                                                "filter.OemBackslashkey",
                                                "filter.F1key",
                                                "filter.F2key",
                                                "filter.F3key",
                                                "filter.F4key",
                                                "filter.F5key",
                                                "filter.F6key",
                                                "filter.F7key",
                                                "filter.F8key",
                                                "filter.F9key",
                                                "filter.F10key",
                                                "filter.F11key",
                                                "filter.F12key",
                                                "filter.Shiftkey",
                                                "filter.Controlkey",
                                                "filter.Altkey",
                                                "filter.Windowskey",
                                                "filter.player1",
                                                "filter.player2",
                                                "filter.player3",
                                                "filter.player4",
                                                "filter.terrain",
                                                "filter.water",
                                                "filter.quartersecond",
                                                "filter.01second",
                                                "filter.02second",
                                                "filter.03second",
                                                "filter.04second",
                                                "filter.05second",
                                                "filter.10second",
                                                "filter.20second",
                                                "filter.30second",
                                                "filter.60second",
                                                "filter.000point",
                                                "filter.001point",
                                                "filter.002point",
                                                "filter.003point",
                                                "filter.004point",
                                                "filter.005point",
                                                "filter.010point",
                                                "filter.020point",
                                                "filter.050point",
                                                "filter.100point",
                                                "filter.random",
                                                "filter.scorebucket.color.white",
                                                "filter.scorebucket.color.black",
                                                "filter.scorebucket.color.grey",
                                                "filter.scorebucket.color.red",
                                                "filter.scorebucket.color.green",
                                                "filter.scorebucket.color.blue",
                                                "filter.scorebucket.color.orange",
                                                "filter.scorebucket.color.yellow",
                                                "filter.scorebucket.color.purple",
                                                "filter.scorebucket.color.pink",
                                                "filter.scorebucket.color.brown",
                                                "filter.scorebucket.letter.a",
                                                "filter.scorebucket.letter.b",
                                                "filter.scorebucket.letter.c",
                                                "filter.scorebucket.letter.d",
                                                "filter.scorebucket.letter.e",
                                                "filter.scorebucket.letter.f",
                                                "filter.scorebucket.letter.g",
                                                "filter.scorebucket.letter.h",
                                                "filter.scorebucket.letter.i",
                                                "filter.scorebucket.letter.j",
                                                "filter.scorebucket.letter.k",
                                                "filter.scorebucket.letter.l",
                                                "filter.scorebucket.letter.m",
                                                "filter.scorebucket.letter.n",
                                                "filter.scorebucket.letter.o",
                                                "filter.scorebucket.letter.p",
                                                "filter.scorebucket.letter.q",
                                                "filter.scorebucket.letter.r",
                                                "filter.scorebucket.letter.s",
                                                "filter.scorebucket.letter.t",
                                                "filter.scorebucket.letter.u",
                                                "filter.scorebucket.letter.v",
                                                "filter.scorebucket.letter.w",
                                                "filter.scorebucket.letter.x",
                                                "filter.scorebucket.letter.y",
                                                "filter.scorebucket.letter.z",
                                                "filter.scorebucket.letter.a",
                                                "filter.scoretrigger",
                                                "filter.timertrigger",
                                                "filter.scoreis",
                                                "filter.scoreabove",
                                                "filter.scorebelow",
                                                "filter.healthis",
                                                "filter.healthabove",
                                                "filter.healthbelow",
                                                "filter.direction.up",
                                                "filter.direction.right",
                                                "filter.direction.down",
                                                "filter.direction.left",
                                                "filter.not",


                                             };

        public static String[] upidModifiers = {
                                                   "modifier.taska",
                                                   "modifier.taskb",
                                                   "modifier.taskc",
                                                   "modifier.taskd",
                                                   "modifier.taske",
                                                   "modifier.taskf",
                                                   "modifier.taskg",
                                                   "modifier.taskh",
                                                   "modifier.taski",
                                                   "modifier.taskj",
                                                   "modifier.taskk",
                                                   "modifier.taskl",
                                                   "modifier.expresshappy",
                                                   "modifier.expresssad",
                                                   "modifier.expressangry",
                                                   "modifier.expresscrazy",
                                                   "modifier.expresshearts",
                                                   "modifier.expressflowers",
                                                   "modifier.expressstars",
                                                   "modifier.expressswear",
                                                   "modifier.expressnone",
                                                   "modifier.000point",
                                                   "modifier.001point",
                                                   "modifier.002points",
                                                   "modifier.003points",
                                                   "modifier.004points",
                                                   "modifier.005points",
                                                   "modifier.010points",
                                                   "modifier.020points",
                                                   "modifier.050points",
                                                   "modifier.100points",
                                                   "modifier.random",
                                                   "modifier.teama",
                                                   "modifier.teamb",
                                                   "modifier.payloadzap",
                                                   "modifier.payloadpop",
                                                   "modifier.payloadboom",
                                                   "modifier.payloadvanish",
                                                   "modifier.black",
                                                   "modifier.grey",
                                                   "modifier.white",
                                                   "modifier.red",
                                                   "modifier.orange",
                                                   "modifier.yellow",
                                                   "modifier.green",
                                                   "modifier.blue",
                                                   "modifier.purple",
                                                   "modifier.pink",
                                                   "modifier.brown",
                                                   "modifier.glowoff",
                                                   "modifier.colorrandom",
                                                   "modifier.scorebucket.color.white",
                                                   "modifier.scorebucket.color.black",
                                                   "modifier.scorebucket.color.grey",
                                                   "modifier.scorebucket.color.red",
                                                   "modifier.scorebucket.color.green",
                                                   "modifier.scorebucket.color.blue",
                                                   "modifier.scorebucket.color.orange",
                                                   "modifier.scorebucket.color.yellow",
                                                   "modifier.scorebucket.color.purple",
                                                   "modifier.scorebucket.color.pink",
                                                   "modifier.scorebucket.color.brown",
                                                   "modifier.scorebucket.letter.a",
                                                   "modifier.scorebucket.letter.b",
                                                   "modifier.scorebucket.letter.c",
                                                   "modifier.scorebucket.letter.d",
                                                   "modifier.scorebucket.letter.e",
                                                   "modifier.scorebucket.letter.f",
                                                   "modifier.scorebucket.letter.g",
                                                   "modifier.scorebucket.letter.h",
                                                   "modifier.scorebucket.letter.i",
                                                   "modifier.scorebucket.letter.j",
                                                   "modifier.scorebucket.letter.k",
                                                   "modifier.scorebucket.letter.l",
                                                   "modifier.scorebucket.letter.m",
                                                   "modifier.scorebucket.letter.n",
                                                   "modifier.scorebucket.letter.o",
                                                   "modifier.scorebucket.letter.p",
                                                   "modifier.scorebucket.letter.q",
                                                   "modifier.scorebucket.letter.r",
                                                   "modifier.scorebucket.letter.s",
                                                   "modifier.scorebucket.letter.t",
                                                   "modifier.scorebucket.letter.u",
                                                   "modifier.scorebucket.letter.v",
                                                   "modifier.scorebucket.letter.w",
                                                   "modifier.scorebucket.letter.x",
                                                   "modifier.scorebucket.letter.y",
                                                   "modifier.scorebucket.letter.z",
                                                   "modifier.me",
                                                   "modifier.it",
                                                   "modifier.any",
                                                   "modifier.event.any",
                                                   "modifier.event.silly.any",
                                                   "modifier.event.silly.bang",
                                                   "modifier.event.silly.pow",
                                                   "modifier.event.explode.any",
                                                   "modifier.event.explode.A",
                                                   "modifier.event.explode.B",
                                                   "modifier.event.explode.C",
                                                   "modifier.event.explode.D",
                                                   "modifier.event.explode.E",
                                                   "modifier.event.musical.any",
                                                   "modifier.event.musical.glock.any",
                                                   "modifier.event.musical.glock01",
                                                   "modifier.event.musical.glock02",
                                                   "modifier.event.musical.glock03",
                                                   "modifier.event.musical.glock04",
                                                   "modifier.event.musical.glock05",
                                                   "modifier.event.musical.glock06",
                                                   "modifier.event.musical.glock07",
                                                   "modifier.event.musical.glock08",
                                                   "modifier.event.musical.glock09",
                                                   "modifier.event.musical.glock10",
                                                   "modifier.event.musical.glock11",
                                                   "modifier.event.musical.glock12",
                                                   "modifier.event.musical.gong.any",
                                                   "modifier.event.musical.gong01",
                                                   "modifier.event.musical.gong02",
                                                   "modifier.event.musical.gong03",
                                                   "modifier.event.musical.gong04",
                                                   "modifier.event.musical.gong05",
                                                   "modifier.event.musical.gong06",
                                                   "modifier.event.musical.gong07",
                                                   "modifier.event.musical.gong08",
                                                   "modifier.event.musical.gong09",
                                                   "modifier.event.musical.gong10",
                                                   "modifier.event.musical.gong11",
                                                   "modifier.event.musical.gong12",
                                                   "modifier.event.musical.saw.any",
                                                   "modifier.event.musical.saw01",
                                                   "modifier.event.musical.saw02",
                                                   "modifier.event.musical.saw03",
                                                   "modifier.event.musical.saw04",
                                                   "modifier.event.musical.saw05",
                                                   "modifier.event.musical.saw06",
                                                   "modifier.event.musical.saw07",
                                                   "modifier.event.musical.saw08",
                                                   "modifier.event.musical.saw09",
                                                   "modifier.event.musical.saw10",
                                                   "modifier.event.musical.saw11",
                                                   "modifier.event.musical.saw12",
                                                   "modifier.event.musical.sine.any",
                                                   "modifier.event.musical.sine01",
                                                   "modifier.event.musical.sine02",
                                                   "modifier.event.musical.sine03",
                                                   "modifier.event.musical.sine04",
                                                   "modifier.event.musical.sine05",
                                                   "modifier.event.musical.sine06",
                                                   "modifier.event.musical.sine07",
                                                   "modifier.event.musical.sine08",
                                                   "modifier.event.musical.sine09",
                                                   "modifier.event.musical.sine10",
                                                   "modifier.event.musical.sine11",
                                                   "modifier.event.musical.sine12",
                                                   "modifier.event.musical.square.any",
                                                   "modifier.event.musical.square01",
                                                   "modifier.event.musical.square02",
                                                   "modifier.event.musical.square03",
                                                   "modifier.event.musical.square04",
                                                   "modifier.event.musical.square05",
                                                   "modifier.event.musical.square06",
                                                   "modifier.event.musical.square07",
                                                   "modifier.event.musical.square08",
                                                   "modifier.event.musical.square09",
                                                   "modifier.event.musical.square10",
                                                   "modifier.event.musical.square11",
                                                   "modifier.event.musical.square12",
                                                   "modifier.event.musical.drums.any",
                                                   "modifier.event.musical.bassdrum",
                                                   "modifier.event.musical.hhclosed",
                                                   "modifier.event.musical.hhopen",
                                                   "modifier.event.musical.shaker",
                                                   "modifier.event.musical.snare",
                                                   "modifier.event.musical.tomlow",
                                                   "modifier.event.musical.tommed",
                                                   "modifier.event.musical.tomhi",
                                                   "modifier.event.arcade.any",
                                                   "modifier.event.arcade.roboton",
                                                   "modifier.event.arcade.robotoff",
                                                   "modifier.event.arcade.coinsound",
                                                   "modifier.event.arcade.gethealth",
                                                   "modifier.event.arcade.losehealth",
                                                   "modifier.event.arcade.shoot",
                                                   "modifier.event.arcade.timer",
                                                   "modifier.event.arcade.win",
                                                   "modifier.event.arcade.lose",
                                                   "modifier.event.misc.any",
                                                   "modifier.event.misc.firepoof",
                                                   "modifier.event.misc.forcefieldup",
                                                   "modifier.event.misc.forcefielddown",
                                                   "modifier.event.misc.hide",
                                                   "modifier.event.misc.lockontarget",
                                                   "modifier.event.misc.losetarget",
                                                   "modifier.event.misc.positivecondition",
                                                   "modifier.event.misc.negativecondition",
                                                   "modifier.event.misc.pop",
                                                   "modifier.event.misc.popout",
                                                   "modifier.event.misc.powerup",
                                                   "modifier.event.misc.servo",
                                                   "modifier.event.misc.watersplash",
                                                   "modifier.event.misc.waterdrop",
                                                   "modifier.event.misc.tagbase",
                                                   "modifier.event.misc.whistlehuman",
                                                   "modifier.event.misc.whistlereferee",
                                                   "modifier.music.any",
                                                   "modifier.music.omni.any",
                                                   "modifier.mu_action",
                                                   "modifier.mu_ambientlight",
                                                   "modifier.mu_ambinetmodd",
                                                   "modifier.mu_brightdowntempo",
                                                   "modifier.mu_brightfunk",
                                                   "modifier.mu_brightguitar",
                                                   "modifier.mu_kodu",
                                                   "modifier.music.mystery.any",
                                                   "modifier.mysterya",
                                                   "modifier.mysteryb",
                                                   "modifier.mysteryc",
                                                   "modifier.music.driving.any",
                                                   "modifier.drivinga",
                                                   "modifier.drivingb",
                                                   "modifier.drivingc",
                                                   "modifier.music.drama.any",
                                                   "modifier.dramaa",
                                                   "modifier.dramab",
                                                   "modifier.environ.any",
                                                   "modifier.environ.ambocean",
                                                   "modifier.environ.ambforest",
                                                   "modifier.environ.ambcity",
                                                   "modifier.environ.ambmeadow",
                                                   "modifier.environ.arena.any",
                                                   "modifier.environ.arena.a",
                                                   "modifier.environ.arena.b",
                                                   "modifier.environ.arena.c",
                                                   "modifier.environ.arena.d",
                                                   "modifier.environ.arena.e",
                                                   "modifier.environ.arena.f",
                                                   "modifier.environ.arena.g",
                                                   "modifier.trackingnone",
                                                   "modifier.trackinghoming",
                                                   "modifier.constraint.leftright",
                                                   "modifier.constraint.fwdback",
                                                   "modifier.constraint.updown",
                                                   "modifier.constraint.northsouth",
                                                   "modifier.constraint.eastwest",
                                                   "modifier.constraint.immobile",
                                                   "modifier.once",
                                                   "modifer.objectsoccerball",
                                                   "modifer.objectbullet",
                                                   "modifier.objectheart",
                                                   "modifier.objectcoin",
                                                   "modifier.objectstar",
                                                   "modifier.objectfruit",
                                                   "modifier.objectrock",
                                                   "modifier.objectrockLowValue",
                                                   "modifier.objectrockHighValue",
                                                   "modifier.distance.far",
                                                   "modifier.distance.near",
                                                   "modifier.down",
                                                   "modifier.up",
                                                   "modifier.west",
                                                   "modifier.south",
                                                   "modifier.east",
                                                   "modifier.north",
                                                   "modifier.forward",
                                                   "modifier.pitchdown",
                                                   "modifier.pitchup",
                                                   "modifier.turnforward",
                                                   "modifier.turntoward",
                                                   "modifier.turnright",
                                                   "modifier.turnleft",
                                                   "modifier.angle.high",
                                                   "modifier.angle.low",
                                                   "modifier.strengthnormally",
                                                   "modifier.strongly",
                                                   "modifier.weakly",
                                                   "modifier.speednormally",
                                                   "modifier.quickly",
                                                   "modifier.slowly",
                                                   "modifier.projectile.missile",
                                                   "modifier.projectile.blip",
                                                   "modifier.reset.health",
                                                   "modifier.reset.glow",
                                                   "modifier.reset.expression",
                                                   "modifier.reset.score",
                                                   "modifier.reset.world",
                                                   "modifier.player.1",
                                                   "modifier.player.2",
                                                   "modifier.player.3",
                                                   "modifier.player.4",
                                                   "modifier.creatable.",
                                               };

    }
}
